on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: node app.js
      - name: Print Something
        run: echo "Gilberto Emilio Ybarra Ibarra"
      - name: Print Something 2 
        run: echo npm --version
      - name: Print Something 3
        run: echo "735579"

